basePath: /
definitions:
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  tasks.CreateTaskRequest:
    properties:
      title:
        type: string
    type: object
  tasks.PaginatedTasksResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/tasks.Task'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  tasks.Task:
    properties:
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
  tasks.UpdateTaskRequest:
    properties:
      done:
        type: boolean
      title:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Scalable Task CRUD API built with Go and SQLite.
  title: Task API
  version: "1.0"
paths:
  /tasks:
    get:
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tasks.PaginatedTasksResponse'
      summary: List all tasks with pagination
      tags:
      - tasks
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/tasks.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/tasks.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Create task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Delete task
      tags:
      - tasks
    get:
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tasks.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get task by ID
      tags:
      - tasks
    put:
      consumes:
      - application/json
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/tasks.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tasks.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Update task
      tags:
      - tasks
swagger: "2.0"
